language: python
python:
    - "2.7"
install: pip install -r requirements.txt
before_script:
  - psql -c 'create database blogful;' -U postgres
script:
    - PYTHONPATH=. python tests/test_filters.py
    - PYTHONPATH=. python tests/test_views_integration.py
    - PYTHONPATH=. python tests/test_views_acceptance.py
    # Add any other tests here

