"""empty message

Revision ID: 2a462d5a4c4a
Revises: None
Create Date: 2014-06-16 14:53:50.885854

"""

# revision identifiers, used by Alembic.
revision = '2a462d5a4c4a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('author_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'author_id')
    ### end Alembic commands ###
