"""empty message

Revision ID: 4ae043d059f2
Revises: 2a462d5a4c4a
Create Date: 2014-06-17 11:35:32.434029

"""

# revision identifiers, used by Alembic.
revision = '4ae043d059f2'
down_revision = '2a462d5a4c4a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
